import {StyleSheet} from 'react-native';

export const authColors = {
  screenBg: '#e0e8f5',
  cardBg: '#ffffff',
  primaryButton: '#eeb200',
  primaryButtonText: '#1a1a1a',
  titleText: '#152a4a',
  brandNavy: '#152a4a',
  brandGold: '#d4a017',
  inputBg: '#ffffff',
  inputBorder: '#cdd5e0',
  inputText: '#1e293b',
  labelText: '#3b4a60',
  placeholderText: '#94a3b8',
  mutedText: '#64748b',
  linkText: '#475569',
  errorText: '#dc2626',
  checkboxActive: '#eeb200',
  shadowColor: '#7a8fad',
};

export const authStyles = StyleSheet.create({
  screenScroll: {
    flexGrow: 1,
    justifyContent: 'center',
    backgroundColor: authColors.screenBg,
    paddingHorizontal: 22,
    paddingVertical: 36,
  },
  brandRow: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  brandSol: {
    fontSize: 28,
    fontWeight: '800',
    color: authColors.brandNavy,
  },
  brandMate: {
    fontSize: 28,
    fontWeight: '800',
    color: authColors.brandGold,
  },
  pageTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: authColors.titleText,
    marginBottom: 20,
  },
  card: {
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    backgroundColor: authColors.cardBg,
    borderRadius: 22,
    paddingHorizontal: 22,
    paddingVertical: 28,
    shadowColor: authColors.shadowColor,
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 6,
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: authColors.labelText,
    marginBottom: 6,
  },
  input: {
    height: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: authColors.inputBorder,
    backgroundColor: authColors.inputBg,
    paddingHorizontal: 16,
    fontSize: 15,
    color: authColors.inputText,
    marginBottom: 16,
  },
  passwordWrap: {
    position: 'relative',
  },
  passwordInput: {
    paddingRight: 52,
  },
  eyeBtn: {
    position: 'absolute',
    right: 12,
    top: 11,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eyeShape: {
    width: 22,
    height: 14,
    borderRadius: 11,
    borderWidth: 1.6,
    borderColor: authColors.mutedText,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'visible',
  },
  eyePupil: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: authColors.mutedText,
  },
  eyeSlash: {
    position: 'absolute',
    width: 1.6,
    height: 24,
    backgroundColor: authColors.mutedText,
    transform: [{rotate: '45deg'}],
  },
  errorText: {
    color: authColors.errorText,
    fontSize: 13,
    marginBottom: 14,
    textAlign: 'center',
  },
  primaryBtn: {
    marginTop: 6,
    height: 52,
    borderRadius: 26,
    backgroundColor: authColors.primaryButton,
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryBtnDisabled: {
    opacity: 0.65,
  },
  primaryBtnText: {
    color: authColors.primaryButtonText,
    fontSize: 17,
    fontWeight: '700',
  },
  bottomLink: {
    marginTop: 20,
    alignItems: 'center',
  },
  bottomLinkText: {
    color: authColors.linkText,
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
  },
  bottomLinkBold: {
    color: authColors.titleText,
    fontWeight: '700',
  },
  rememberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 2,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: authColors.inputBorder,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  checkboxChecked: {
    backgroundColor: authColors.checkboxActive,
    borderColor: authColors.checkboxActive,
  },
  checkboxMark: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  rememberTextWrap: {
    flex: 1,
  },
  rememberLabel: {
    color: authColors.titleText,
    fontSize: 14,
    fontWeight: '600',
  },
  rememberHint: {
    color: authColors.mutedText,
    fontSize: 12,
    marginTop: 2,
  },
});
