import { StyleSheet } from 'react-native';
import {solmateColors} from '../src/theme/colors';

export const authColors = {
  screenBg: solmateColors.background,
  cardBg: solmateColors.white,
  primaryButton: solmateColors.primary,
  primaryButtonText: solmateColors.text,
  titleText: solmateColors.text,
  brandNavy: solmateColors.navy,
  brandGold: solmateColors.primary,
  inputBg: solmateColors.background,
  inputBorder: solmateColors.border,
  inputText: solmateColors.text,
  labelText: solmateColors.navy,
  placeholderText: solmateColors.mutedSoft,
  mutedText: solmateColors.muted,
  linkText: solmateColors.accentStrong,
  errorText: solmateColors.danger,
  errorBg: '#FFF7F7',
  errorIconBg: '#FFE6E6',
  errorCopyText: '#8F2D2D',
  successBg: solmateColors.navy,
  successBorder: solmateColors.accentSky,
  successText: solmateColors.white,
  successMutedText: 'rgba(255,255,255,0.78)',
  successBadgeBg: 'rgba(125, 223, 242, 0.2)',
  successBadgeText: solmateColors.accentSky,
  checkboxActive: solmateColors.primary,
  shadowColor: solmateColors.shadow,
};

export const authStyles = StyleSheet.create({
  screenContainer: {
    flex: 1,
    backgroundColor: authColors.screenBg,
  },
  screenScroll: {
    flexGrow: 1,
    justifyContent: 'center',
    backgroundColor: authColors.screenBg,
    paddingHorizontal: 22,
    paddingVertical: 36,
  },
  screenScrollLandscape: {
    justifyContent: 'flex-start',
    paddingVertical: 24,
  },
  screenScrollCompact: {
    paddingHorizontal: 16,
    paddingVertical: 24,
  },
  brandRow: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  brandSol: {
    fontSize: 28,
    fontWeight: '800',
    color: authColors.brandNavy,
  },
  brandMate: {
    fontSize: 28,
    fontWeight: '800',
    color: authColors.brandGold,
  },
  pageTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: authColors.titleText,
    marginBottom: 20,
  },
  card: {
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    backgroundColor: authColors.cardBg,
    borderRadius: 22,
    paddingHorizontal: 22,
    paddingVertical: 28,
    shadowColor: authColors.shadowColor,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 6,
  },
  cardCompact: {
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 22,
  },
  cardLandscape: {
    maxWidth: 460,
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: authColors.labelText,
    marginBottom: 6,
  },
  input: {
    height: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: authColors.inputBorder,
    backgroundColor: authColors.inputBg,
    paddingHorizontal: 16,
    fontSize: 15,
    color: authColors.inputText,
    marginBottom: 16,
  },
  passwordWrap: {
    position: 'relative',
  },
  passwordInput: {
    paddingRight: 52,
  },
  eyeBtn: {
    position: 'absolute',
    right: 12,
    top: 11,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eyeShape: {
    width: 22,
    height: 14,
    borderRadius: 11,
    borderWidth: 1.6,
    borderColor: authColors.mutedText,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'visible',
  },
  eyePupil: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: authColors.mutedText,
  },
  eyeSlash: {
    position: 'absolute',
    width: 1.6,
    height: 24,
    backgroundColor: authColors.mutedText,
    transform: [{ rotate: '45deg' }],
  },
  errorText: {
    color: authColors.errorCopyText,
    fontSize: 12,
    lineHeight: 17,
  },
  errorBox: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderWidth: 1,
    borderColor: authColors.errorText,
    borderRadius: 16,
    backgroundColor: authColors.errorBg,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 16,
  },
  errorIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: authColors.errorIconBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  errorIconText: {
    color: authColors.errorText,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
  },
  errorCopy: {
    flex: 1,
    paddingTop: 1,
  },
  errorTitle: {
    color: authColors.errorText,
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 2,
  },
  successToast: {
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    marginBottom: 14,
    borderWidth: 1,
    borderColor: authColors.successBorder,
    borderRadius: 18,
    backgroundColor: authColors.successBg,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: authColors.shadowColor,
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 8,
  },
  successToastBadge: {
    alignSelf: 'flex-start',
    overflow: 'hidden',
    borderRadius: 999,
    backgroundColor: authColors.successBadgeBg,
    color: authColors.successBadgeText,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    marginBottom: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    textTransform: 'uppercase',
  },
  successToastTitle: {
    color: authColors.successText,
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 21,
  },
  successToastCopy: {
    color: authColors.successMutedText,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 6,
  },
  helperText: {
    color: authColors.mutedText,
    fontSize: 12,
    lineHeight: 18,
    marginTop: -8,
    marginBottom: 14,
  },
  primaryBtn: {
    marginTop: 6,
    height: 52,
    borderRadius: 26,
    backgroundColor: authColors.primaryButton,
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryBtnDisabled: {
    opacity: 0.65,
  },
  primaryBtnText: {
    color: authColors.primaryButtonText,
    fontSize: 17,
    fontWeight: '700',
  },
  bottomLink: {
    marginTop: 20,
    alignItems: 'center',
  },
  bottomLinkText: {
    color: authColors.linkText,
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
  },
  bottomLinkBold: {
    color: authColors.titleText,
    fontWeight: '700',
  },
  rememberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 2,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: authColors.inputBorder,
    backgroundColor: solmateColors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  checkboxChecked: {
    backgroundColor: authColors.checkboxActive,
    borderColor: authColors.checkboxActive,
  },
  checkboxMark: {
    color: solmateColors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  rememberTextWrap: {
    flex: 1,
  },
  rememberLabel: {
    color: authColors.titleText,
    fontSize: 14,
    fontWeight: '600',
  },
  rememberHint: {
    color: authColors.mutedText,
    fontSize: 12,
    marginTop: 2,
  },
});
